const PI = Math.PI;

var r = {};

r.replace = function(answers) {
    if(answers.indexOf('°±')!=-1&&answers.indexOf('µª')!=-1) answers = answers.replace(/°±/g, "º¤");
    if(answers.indexOf('¸ê')!=-1&&answers.indexOf('Ã¬')!=-1) answers = answers.replace(/ÔØ/g, "êª");
    if(answers.indexOf('Ì©')!=-1&&answers.indexOf('Ó£')!=-1) answers = answers.replace(/Ì©/g, "İÄ");
    if(answers.indexOf('Ôµ')!=-1&&answers.indexOf('Ë´')!=-1) answers = answers.replace(/Ôµ/g, "öç");
    if(answers.indexOf('·ÅËÉ»î¶¯')!=-1&&answers.indexOf('»ù±¾»î¶¯')!=-1) answers = answers.replace(/Ò»/g, "");
    if(answers.indexOf('¼­ÄÃ')!=-1&&answers.indexOf('ÉşÄÃ')!=-1) answers = answers.replace(/ÉşÄÃ/g, "¼©ÄÃ");
    if(answers.indexOf('»Æº£')!=-1&&answers.indexOf('³±º£')!=-1) answers = answers.replace(/³±º£/g, "²³º£");
    answers = answers.replace(/¸ÂÁë/g, "àÑßÊ");
    answers = answers.replace(/´ËÄØ·çÔÆ/g, "ß³ßå·çÔÆ");
    answers = answers.replace(/ÈÜÁ¶/g, "´ãÁ¶");
    answers = answers.replace(/ÉùÃûÔÏÆğ/g, "ÉùÃûÈµÆğ");
    answers = answers.replace(/õõÏÊ/g, "õõ²õ");
    answers = answers.replace(/cuotud/g, "cu¨­tu¨®");
    answers = answers.replace(/ÓÆÆø/g, "±ïÆø");
    answers = answers.replace(/0ĞÍ/g, "OĞÍ");
    answers = answers.replace(/oĞÍ/g, "OĞÍ");
    answers = answers.replace(/¼ÈÍù²»ÖÇ/g, "¼ÈÍù²»¾Ì");
    answers = answers.replace(/¼Ì½ÅÊ¯/g, "°í½ÅÊ¯");
    answers = answers.replace(/ÑİºÏ/g, "´ÕºÏ");
    answers = answers.replace(/Áõ·­/g, "ÁõÛÄ");
    answers = answers.replace(/ÇéÀÁ/g, "ã¼ÀÁ");
    answers = answers.replace(/ºÓºº/g, "ºÓãâ");
    answers = answers.replace(/Ğ»¼¡/g, "Ğ»–I");
    answers = answers.replace(/Òï½ÅÊ¯/g, "°í½ÅÊ¯");
    answers = answers.replace(/ĞŞÓª/g, "ĞŞİİ");
    answers = answers.replace(/ì³Ğã/g, "ÅáĞã");
    answers = answers.replace(/ôäĞã/g, "ÅáĞã");
    answers = answers.replace(/Å«æ¾bi/g, "Å«æ¾b¨¬");
    answers = answers.replace(/Å«bi/g, "Å«æ¾b¨¬");
    answers = answers.replace(/±­ÅÌÀÇ¾«/g, "±­ÅÌÀÇ½å");
    answers = answers.replace(/ÓĞÌØÎŞ¿Ö/g, "ÓĞÊÑÎŞ¿Ö");
    answers = answers.replace(/ºÉ×Ó/g, "Ü÷×Ó");
    answers = answers.replace(/ÕôÏÚË®/g, "ÕôÁóË®");
    answers = answers.replace(/´ÖÀ©/g, "´Öáî");
    answers = answers.replace(/¶ß¾ş/g, "†ªËô");
    answers = answers.replace(/ücÈ»Ê§É«/g, "÷öÈ»Ê§É«");
    answers = answers.replace(/chaigian/g, "chaiqian");
    answers = answers.replace(/²îÔì/g, "²îÇ²");
    answers = answers.replace(/ÇàÓªËØ/g, "ÇàİïËØ");
    answers = answers.replace(/Å«¹º/g, "Å«æ¾");
    answers = answers.replace(/×ìÖ®ÒÔ±Ç/g, "àÍÖ®ÒÔ±Ç");
    answers = answers.replace(/¿îÊÕ/g, "Ç¸ÊÕ");
    answers = answers.replace(/Á´¶ø×ßÏÕ/g, "îú¶ø×ßÏÕ");
    answers = answers.replace(/Ä¸¿µÖÃÒÉ/g, "ÎãÓ¹ÖÃÒÉ");
    answers = answers.replace(/JI/g, "´¨");
    answers = answers.replace(/½Ğ¿à²»ËÍ/g, "½Ğ¿à²»µü");
    answers = answers.replace(/³æºú/g, "ºû");
    answers = answers.replace(/ÓãÀğ/g, "Óã÷§");
    answers = answers.replace(/³ÁÃå/g, "³ÁäÏ");
    answers = answers.replace(/±íĞã/g, "ÅáĞã");
    answers = answers.replace(/ÔóÁ¶/g, "´ãÁ¶");
    answers = answers.replace(/bu/g, "b¨´");
    answers = answers.replace(/ÏÄÈ»¶øÖ¹/g, "ê©È»¶øÖ¹");
    answers = answers.replace(/µæ·ü/g, "Õİ·ü");
    answers = answers.replace(/´ÓÎÒ/g, "´ÓÈÖ");
    answers = answers.replace(/¿çÌ¤/g, "³ì³ù");
    answers = answers.replace(/Æ¯Áë/g, "àÑßÊ");
    answers = answers.replace(/¿ìÃÜ/g, "¾÷ÇÏ");
    answers = answers.replace(/¾öÃÜ/g, "¾÷ÇÏ");
    answers = answers.replace(/ÁîæÂ/g, "ÁîæÈ");
    answers = answers.replace(/Öì½İ/g, "Öìé¦");
    answers = answers.replace(/ÎíäÁ/g, "ÎíÚ¡");
    answers = answers.replace(/.Ñôºş/g, "ÅËÑôºş");
    answers = answers.replace(/ÅâÈ»Ê§É«/g, "÷öÈ»Ê§É«");
    answers = answers.replace(/ÏàĞÎ¼ûÏ¸/g, "ÏàĞÎ¼ûç©");
    answers = answers.replace(/Òû¸ëÖ¹¿Ê/g, "Òûğ²Ö¹¿Ê");
    answers = answers.replace(/ºÎ×å/g, "¶±×å");
    answers = answers.replace(/ÇĞÌ¼/g, "ÇĞ´è");
    answers = answers.replace(/²»Ê¤¶ø×ß/g, "²»ëÖ¶ø×ß");
    answers = answers.replace(/\+/g, "Ê®");
    answers = answers.replace(/Àî³Ï/g, "Àî½ë");
    answers = answers.replace(/êÍºì/g, "´Úºì");
    answers = answers.replace(/Ìãºì/g, "´Úºì");
    return answers
};

module.exports = r;